services:
  db:
    image: postgres:16-alpine
    container_name: footquiz_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fifa
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fifa"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  app:
    build: .
    container_name: footquiz_app
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/fifa
      DAILY_SCRAPE_HOUR: "22"
      DAILY_SCRAPE_MINUTE: "0"
      FLARESOLVERR_URL: http://atw_flaresolverr:8191
    ports:
      - "8080:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - default
      - atw_net

networks:
  atw_net:
    external: true
    name: pfe-project_atw_net

volumes:
  pgdata:
    name: footquiz_pgdata